### ISSUE TITLE
Is it necessary to push spans onto thread_local if they are not sampled?

### ISSUE THREAD

**Issue by Jefftree** [Yelp/py_zipkin#59] opened 2017-08-10 21:00 UTC
Consider a case where the root span has a very low sampling rate and there are a bunch of nested zipkin spans. 

```
with zipkin_span(...):
    with zipkin_span(...):
        ...
```
If the trace is not sampled, the root span's `is_sampled` flag will be false, and the span will not be logged. However we are still generating a new span after entering each `zipkin_span` context and pushing the span onto thread local. 

https://github.com/Yelp/py_zipkin/blob/master/py_zipkin/zipkin.py#L264

and 

https://github.com/Yelp/py_zipkin/blob/master/py_zipkin/zipkin.py#L280

This newly generated span is not used for logging (since `is_sampled` is false) and there is really no need to push and pop it from the stack. The total time to generate/push/pop this span from thread local is not very significant, but this adds up for a service with many nested spans.

Can we do an additional check for whether a span is sampled before generating its parameters and pushing it onto thread_local?

**Comment by adriancole** [comment] 2017-08-11 00:34
I am not sure of the log correlation practice in python, but in java we
keep spans regardless of sampling so that log files (not in zipkin) can be
tokenized against a consistent ID. This means when you have a problem you
can log correlate even if unlucky with trace sampling.

So depends on if there are any such non-tracing consumers of these ids.

On 11 Aug 2017 5:00 am, "Jeffrey Ying" <notifications@github.com> wrote:

Consider a case where the root span has a very low sampling rate and there
are a bunch of nested zipkin spans.

with zipkin_span(...):
    with zipkin_span(...):
        ...

If the trace is not sampled, the root span's is_sampled flag will be false,
and the span will not be logged. However we are still generating a new span
after entering each zipkin_span context and pushing the span onto thread
local.

https://github.com/Yelp/py_zipkin/blob/master/py_zipkin/zipkin.py#L264

and

https://github.com/Yelp/py_zipkin/blob/master/py_zipkin/zipkin.py#L280

This newly generated span is not used for logging (since is_sampled is
false) and there is really no need to push and pop it from the stack. The
total time to generate/push/pop this span from thread local is not very
significant, but this adds up for a service with many nested spans.

Can we do an additional check for whether a span is sampled before
generating its parameters and pushing it onto thread_local?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Yelp/py_zipkin/issues/59>, or mute the thread

**Comment by Jefftree** [comment] 2017-08-11 01:24
For log correlation, the most important id is probably the trace id which is only generated once at the beginning of the request. This can be propagated without going through the process of generating a span, span id and inheriting the trace id for every instance of entering the `zipkin_span` context.

**Comment by adriancole** [comment] 2017-08-11 01:37
@Jefftree I think it is a judgement call, for example some are scraping logs for operation-scoped queries. Also, in multi-threaded situations the span ID helps. Anyway food for thought, whatever done should be documented.

**Comment by adriancole** [comment] 2017-08-11 01:39
for example you might look at https://github.com/census-instrumentation/opencensus-python which if like the java side also keeps span ID even when unsampled (not exported).

**Comment by bplotnick** [comment] 2017-08-11 18:36
@adriancole based on a quick read, it looks like they don't actually create the span object on an unsampled trace - https://github.com/census-instrumentation/opencensus-python/blob/master/trace/opencensus/trace/tracer/context_tracer.py#L127 (at least for the ContextTracer). Additionally, they don't seem to do in-process context propagation automatically, which is something we made the decision to do. The downside being that we don't support multithreaded cases since we use thread-local storage to store the trace context.

I see what you're saying about creating a span object even in the unsampled case, and I don't think that it would be _too_ hard to do, though at the moment we really don't have an idea of a separate span object. I think we'd need to first refactor to break apart spans vs traces vs the tracer/sampling logic - a refactor that i think is certainly needed.

OTOH, I don't think that we have seen enough of a use case to prioritize it now. However, the problem that this issue is trying to address is one particular case where we have hundreds of spans in a single request context in a single process, so the untraced overhead can add up - though in all honesty it is probably a drop in the bucket compared to the rest of the request *shrug*

**Comment by adriancole** [comment] 2017-08-12 00:55
>
> @adriancole <https://github.com/adriancole> based on a quick read, it
> looks like they don't actually create the span object on an unsampled trace
> - https://github.com/census-instrumentation/opencensus-
> python/blob/master/trace/opencensus/trace/tracer/context_tracer.py#L127
> (at least for the ContextTracer). Additionally, they don't seem to do
> in-process context propagation automatically, which is something we made
> the decision to do. The downside being that we don't support multithreaded
> cases since we use thread-local storage to store the trace context.
>
Thanks for the peek at the python code. It is probably just that the
library is more recent than the java one.

@liyanhui1228 do you know if the python census impl will end up with
"with_span" context propagation similar to the java tracer? (where a span
is placed in context even if it is not sampled for export)


> I see what you're saying about creating a span object even in the
> unsampled case, and I don't think that it would be *too* hard to do,
> though at the moment we really don't have an idea of a separate span
> object. I think we'd need to first refactor to break apart spans vs traces
> vs the tracer/sampling logic - a refactor that i think is certainly needed.
>
In brave/finagle and some others, it is more about a separate trace context
object than a span one. For example, you can pass an unsampled context
(which may already be going on or else you'd not necessarily be able to
propagated unsampled). Ex in brave the noop span is just a wrapped context
which has no sampling bit set.

OTOH, I don't think that we have seen enough of a use case to prioritize it
> now. However, the problem that this issue is trying to address is one
> particular case where we have hundreds of spans in a single request context
> in a single process, so the untraced overhead can add up - though in all
> honesty it is probably a drop in the bucket compared to the rest of the
> request *shrug*
>
Suppose it depends on how long it takes to create a span ID (ex if you are
dropping all events, then you are left with ID creation and the cost of
propagation itself.) All this is separate from priority to do it, or that
it is worth doing. Agreed.

**Comment by liyanhui1228** [comment] 2017-08-14 17:25
@adriancole Currently we do not create spans in the context if not sampled, but if there is use case like you said which needs the span id, we can make the change. For log correlation on Google Cloud, it does not depends on the tracing stuff, the logging client is getting the trace id from request headers which enables correlation on the Cloud Console. Actually our python trace was designed for Google Cloud Stackdriver Trace API previously, and moved to opencensus-python repository recently. So some of the design should be changed because it is no longer just for the Stackdriver Trace.

Thanks for starting the discussion, I'm happy to involve in any discussion about trace and make our design better.

**Comment by adriancole** [comment] 2017-08-15 01:02
>
> Thanks for starting the discussion, I'm happy to involve in any discussion
> about trace and make our design better.
>
Thanks for sharing all this background, Angela! I'm now watching the repo
and will catch you there.

**Comment by bplotnick** [comment] 2017-08-16 21:58
Based on what @Jefftree found in https://github.com/Yelp/pyramid_zipkin/pull/84, it's looking like on the order of 10s of microseconds for the span creation. I'm going to say that we leave this as-is and closing this as won't fix. 

Maybe eventually we can split apart trace context creation and span creation (and only do the former in the case of an unsampled request) as an optimization for high span counts.

**Closed by bplotnick** 2017-08-16 21:58 UTC
