### ISSUE TITLE
py_zipkin span is not accepted by the openzipkin collector.

### ISSUE THREAD

**Issue by travelsalesman** [Yelp/py_zipkin#57] opened 2017-08-07 17:43 UTC
1. Run `docker run -d --net host openzipkin/zipkin`

2. Install py-zipkin `pip install py-zipkin==0.8.3`
2. Run the following python script: 
```
#!/usr/bin/env python

import requests

from py_zipkin.zipkin import zipkin_span

def http_transport(encoded_span):
    # The collector expects a thrift-encoded list of spans.
    requests.post(
        'http://localhost:9411/api/v1/spans',
        data=encoded_span,
        headers={'Content-Type': 'application/x-thrift'},
    )

if __name__ == '__main__':
    with zipkin_span(
        service_name='test_service',
        transport_handler=http_transport,
        sample_rate=100.0,
    ):
        print "Work"
```
I see the following log line in the collector and  get a 400 responce

```
2017-08-07 00:43:04.851  WARN 7 --- [nio-9411-exec-7] zipkin.server.ZipkinHttpCollector        : [Malformed reading List<Span> from TBinary]([url](url))

java.lang.IllegalArgumentException: Malformed reading List<Span> from TBinary
	at zipkin.internal.ThriftCodec.exceptionReading(ThriftCodec.java:600) ~[zipkin-1.29.1.jar!/:na]
	at zipkin.internal.ThriftCodec.readList(ThriftCodec.java:564) ~[zipkin-1.29.1.jar!/:na]
	at zipkin.internal.ThriftCodec.readSpans(ThriftCodec.java:88) ~[zipkin-1.29.1.jar!/:na]
	at zipkin.collector.Collector.acceptSpans(Collector.java:93) ~[zipkin-1.29.1.jar!/:na]
	at zipkin.server.ZipkinHttpCollector.validateAndStoreSpans(ZipkinHttpCollector.java:88) [classes/:na]
	at zipkin.server.ZipkinHttpCollector.uploadSpansThrift(ZipkinHttpCollector.java:73) [classes/:na]
```

**Comment by kaisen** [comment] 2017-08-07 19:27
@travelsalesman we recently made py_zipkin output lists of spans instead of single spans to the transport_handler. I tested your script with py_zipkin==v0.9.0 and it works for me. Can you retry with v0.9.0?

**Comment by bplotnick** [comment] 2017-08-08 03:36
Ah yeah. It looks like only the [Kafka](https://github.com/openzipkin/zipkin/blob/1.19.0/zipkin-collector/kafka/src/main/java/zipkin/collector/kafka/KafkaStreamProcessor.java#L65) collector accepts single spans. The [http](https://github.com/openzipkin/zipkin/blob/1.19.0/zipkin-server/src/main/java/zipkin/server/ZipkinHttpCollector.java) collector and the [scribe](https://github.com/openzipkin/zipkin/blob/1.19.0/zipkin-collector/scribe/src/main/java/zipkin/collector/scribe/ScribeSpanConsumer.java) collector don't.  I guess we only use kafka collector, so we didn't notice it. I wonder if we could have some integration tests to test these.

Anyway, this should be fixed in py_zipkin 0.9.0.

**Comment by adriancole** [comment] 2017-08-08 03:52
indeed "legacy encoding" is single-span (we detect to tell the difference
in kafka)

https://github.com/openzipkin/zipkin/tree/master/zipkin-collector/kafka#kafkacollector

one way to do integration test is via docker (we have images including a
test setup of kafka). another is to emulate zipkin's collector..

**Comment by cybergrind** [comment] 2017-08-28 14:52
I have the error that looks very similar but only with 0.9.0 + opentracing/zipkin via http (0.8.3 works well).
So, definitely, there is some incompatibility introduced between 0.8.3...0.9.0

My code looks like:
```
        timing = {'ss': span.start_time,
                  'sr': span.start_time+span.duration}
        annotations = annotation_list_builder(timing, EP)
        attrs = ZipkinAttrs(trace_id=hex(ctx.trace_id)[2:],,
                            span_id=hex(ctx.span_id)[2:],
                            parent_span_id=span.parent_id and hex(span.parent_id)[2:],
                            flags=0,
                            is_sampled=True)
        params = {
            'zipkin_attrs': attrs,
            'service_name': self.name,
            'span_name': span.operation_name or 'no_name',
            'annotations': annotations,
            'transport_handler': http_transport,
        }
        with self.log_span(**params):
            pass
```

**Comment by adriancole** [comment] 2017-08-28 14:55
>
> I have the error that looks very similar but only with 0.9.0 +
> opentracing/zipkin via http (0.8.3 works well).
>
what do you mean by opentracing/zipkin? did you mean to just say zipkin?
opentracing is neither a server, nor this library

**Comment by cybergrind** [comment] 2017-08-28 15:00
@adriancole  docker image `opentracing/zipkin`

**Comment by adriancole** [comment] 2017-08-29 00:58
>
> @adriancole <https://github.com/adriancole> docker image
> opentracing/zipkin
>
I think you mean openzipkin/zipkin
<https://hub.docker.com/r/openzipkin/zipkin/>, right? OpenZipkin predates
OpenTracing and is not affiliated with it.

**Comment by cybergrind** [comment] 2017-08-29 09:04
@adriancole yeah, my fault. I meant openzipkin/zipkin image

**Comment by adriancole** [comment] 2017-08-29 10:19
Ok thanks for clarifying. So this should be easy to repro as it is the
normal zipkin server (can download jar or use docker)

**Comment by cybergrind** [comment] 2017-08-29 12:04
I believe the core difference is the https://github.com/Yelp/py_zipkin/blob/master/py_zipkin/thrift/__init__.py#L181

My issue was caused by using old http transport code, that basically was:

```
def http_transport(encoded_span):
    # copypasted from: https://github.com/Yelp/py_zipkin#transport
    # The collector expects a thrift-encoded list of spans. Instead of
    # decoding and re-encoding the already thrift-encoded message, we can just
    # add header bytes that specify that what follows is a list of length 1.
    body = b'\x0c\x00\x00\x00\x01' + encoded_span
    requests.post(
        'http://{}/api/v1/spans'.format(ZIPKIN),
        data=body,
        headers={'Content-Type': 'application/x-thrift'},
    )
```

As I understand: b'\x0c\x00\x00\x00\x01' - stands for list with length 1 and 0.9.0 already encodes everything as a list so it doesn't required anymore.

**Comment by cybergrind** [comment] 2017-08-29 12:21
@kaisen @bplotnick if I understand the issue correctly it can be closed now.

**Comment by bplotnick** [comment] 2017-08-29 15:09
@cybergrind Thanks for posting this. We should've been clearer about that backwards incompatibility. Glad you got it resolved.

I'm going to go ahead and close this. Others can open a new issue or reach out on the zipkin gitter if they run into similar problems.

**Closed by bplotnick** 2017-08-29 15:09 UTC
